<script>
	import { onDestroy } from 'svelte';
	import { addToast } from '$lib/stores.js';
	import { coverUrl, formatRelativeTime, parseUTC } from '$lib/utils.js';
	import { Loader2, RefreshCw, Music, Radar, Calendar, Check } from 'lucide-svelte';
	import Card from '../../components/ui/Card.svelte';
	import Button from '../../components/ui/Button.svelte';
	import Badge from '../../components/ui/Badge.svelte';
	import Skeleton from '../../components/ui/Skeleton.svelte';
	import EmptyState from '../../components/ui/EmptyState.svelte';

	let tracks = $state([]);
	let loading = $state(false);
	let fetchedAt = $state(null);
	let lastRefreshed = $state(null);
	let message = $state(null);
	let playlistId = $state(null);
	let runningRefresh = $state(false);

	let _destroyed = false;
	onDestroy(() => { _destroyed = true; });

	let total = $derived(tracks.length);

	async function load() {
		loading = true;
		message = null;
		try {
			const data = await fetch('/api/discovery/weekly-radar').then(r => r.json());
			tracks = data.tracks || [];
			fetchedAt = data.fetched_at;
			lastRefreshed = data.last_refreshed;
			message = data.message || null;
			playlistId = data.playlist_id || null;
		} catch (e) {
			addToast('Failed to load Weekly Radar', 'error');
			tracks = [];
		} finally {
			loading = false;
		}
	}

	async function regenerate() {
		runningRefresh = true;
		try {
			const res = await fetch('/api/schedule/playlist_weekly_discover/run', { method: 'POST' });
			const data = await res.json();
			if (data.error) {
				addToast(data.error, 'error');
				runningRefresh = false;
				return;
			}
			addToast('Regenerating Weekly Discover — check Logs for progress', 'success');
			pollUntilFresh(data.job_id);
		} catch {
			addToast('Failed to start regeneration', 'error');
			runningRefresh = false;
		}
	}

	async function pollUntilFresh(jobId) {
		for (let i = 0; i < 60; i++) {
			if (_destroyed) return;
			await new Promise(r => setTimeout(r, 3000));
			if (_destroyed) return;
			try {
				const job = await fetch(`/api/jobs/${jobId}`).then(r => r.json());
				if (job.status === 'completed') {
					await load();
					runningRefresh = false;
					return;
				}
				if (job.status === 'failed') {
					addToast('Regeneration failed', 'error');
					runningRefresh = false;
					return;
				}
			} catch {}
		}
		runningRefresh = false;
	}

	function formatDate(iso) {
		if (!iso) return '—';
		try {
			return parseUTC(iso).toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' });
		} catch { return iso; }
	}

	$effect(() => { if (!tracks.length && !loading && !message) load(); });
</script>

<!-- Header card with subtitle -->
<Card padding="p-4" class="mb-4">
	<div class="flex flex-wrap items-start gap-3">
		<div class="flex items-start gap-3 flex-1 min-w-0">
			<div class="w-10 h-10 rounded-lg bg-[var(--color-discover)]/15 text-[var(--color-discover)] flex items-center justify-center flex-shrink-0">
				<Radar class="w-5 h-5" />
			</div>
			<div class="min-w-0">
				<div class="flex items-center gap-2 flex-wrap">
					<span class="font-semibold text-[var(--text-primary)]">Weekly Radar</span>
					<span class="text-xs text-[var(--text-muted)]">Refreshes weekly</span>
				</div>
				<div class="text-xs text-[var(--text-secondary)] mt-0.5">
					Auto-curation from your library, generated by the
					<span class="font-mono text-[var(--text-muted)]">playlist_weekly_discover</span> scheduled task.
				</div>
				<div class="mt-1 flex items-center gap-3 text-xs text-[var(--text-muted)]">
					<span class="inline-flex items-center gap-1">
						<Calendar class="w-3 h-3" />
						Last refreshed: <span class="font-mono text-[var(--text-secondary)] ml-1">{formatDate(lastRefreshed)}</span>
						{#if lastRefreshed}
							<span class="text-[var(--text-disabled)]">({formatRelativeTime(lastRefreshed)})</span>
						{/if}
					</span>
					{#if total > 0}
						<span>&middot;</span>
						<span>{total} tracks</span>
					{/if}
				</div>
			</div>
		</div>
		<div class="flex items-center gap-2">
			<Button variant="default" size="sm" onclick={load} loading={loading} disabled={runningRefresh}>
				<RefreshCw class="w-3.5 h-3.5" />
				Reload
			</Button>
			<Button variant="primary" size="sm" onclick={regenerate} loading={runningRefresh}>
				<Radar class="w-3.5 h-3.5" />
				Regenerate
			</Button>
		</div>
	</div>
</Card>

{#if loading && !tracks.length}
	<Card padding="p-0">
		<div class="space-y-0.5">
			{#each Array(8) as _}
				<div class="px-4 py-3 flex items-center gap-4">
					<Skeleton class="h-4 w-8" />
					<Skeleton class="h-10 w-10 rounded" />
					<div class="flex-1 space-y-1.5">
						<Skeleton class="h-4 w-40" />
						<Skeleton class="h-3 w-28" />
					</div>
					<Skeleton class="h-5 w-16 rounded-full" />
				</div>
			{/each}
		</div>
	</Card>
{:else if message}
	<Card>
		<EmptyState title="Weekly Discover hasn't run yet" description={message}>
			{#snippet icon()}<Radar class="w-12 h-12" />{/snippet}
		</EmptyState>
		<div class="flex justify-center mt-3">
			<Button variant="primary" size="sm" onclick={regenerate} loading={runningRefresh}>
				<Radar class="w-3.5 h-3.5" />
				Generate now
			</Button>
		</div>
	</Card>
{:else if !tracks.length}
	<Card>
		<EmptyState title="Weekly Discover is empty" description="Try regenerating, or add more tracks to your library so the auto-curator has something to pick from.">
			{#snippet icon()}<Music class="w-12 h-12" />{/snippet}
		</EmptyState>
	</Card>
{:else}
	<Card padding="p-0">
		<div class="space-y-0.5">
			{#each tracks as t, i}
				<div class="px-4 py-3 flex items-center gap-3 hover:bg-[var(--surface-container-high)] transition-colors">
					<span class="text-[var(--text-disabled)] font-mono text-xs w-6 text-right flex-shrink-0">{i + 1}</span>
					<div class="flex-shrink-0 w-10 h-10 rounded overflow-hidden bg-[var(--surface-container-high)]">
						{#if t.cover_art}
							<img src={coverUrl(t.cover_art)} alt="" class="w-full h-full object-cover" loading="lazy" />
						{:else}
							<div class="w-full h-full flex items-center justify-center">
								<Music class="w-4 h-4 text-[var(--text-disabled)]" />
							</div>
						{/if}
					</div>
					<div class="flex-1 min-w-0">
						<div class="font-medium text-sm text-[var(--text-primary)] truncate">{t.track}</div>
						<div class="text-xs text-[var(--text-secondary)] truncate">
							{t.artist}
							{#if t.album}
								<span class="text-[var(--text-muted)]"> &middot; {t.album}</span>
							{/if}
							{#if t.year}
								<span class="text-[var(--text-disabled)]"> &middot; {t.year}</span>
							{/if}
						</div>
					</div>
					<Badge variant="success">
						<Check class="w-3 h-3" />
						In Library
					</Badge>
				</div>
			{/each}
		</div>
	</Card>
{/if}
