// Live previews of the Google TV visualizer's effects, rendered from the app's own GLSL.
//
// One shared WebGL context does all the drawing: browsers allow only about 16 live contexts,
// and the page shows 93 effects. Each frame it renders every visible card's effect into the
// shared canvas and copies the result onto that card's own 2D canvas. Cards off-screen are
// skipped, so the cost tracks what is on screen, not the size of the catalogue.
//
// The music is simulated: a 120 bpm kick drives the same signals the TV's renderer feeds its
// shaders (bass, kick, spectrum, ripples), so the previews pulse the way the effects do on
// the TV with a song playing. Shader strings come from frontend/static/tv-shaders.json,
// generated by scripts/extract-tv-shaders.py.

const MAX_W = 960;
const MAX_H = 540;
const BEAT_SEC = 0.5; // 120 bpm
const FRAME_MS = 1000 / 30;

let dataPromise = null;

/** The effect catalogue and shader sources, fetched once. */
export function loadTvShaders() {
	if (!dataPromise) {
		dataPromise = fetch('/tv-shaders.json').then((r) => {
			if (!r.ok) throw new Error(`tv-shaders.json: ${r.status}`);
			return r.json();
		});
	}
	return dataPromise;
}

/** A stand-in album cover: bold shapes in three colours, as in the docs gallery. */
function makeCover() {
	const cv = document.createElement('canvas');
	cv.width = cv.height = 256;
	const c = cv.getContext('2d');
	const g = c.createLinearGradient(0, 0, 256, 256);
	g.addColorStop(0, '#1b1446');
	g.addColorStop(1, '#0d3b52');
	c.fillStyle = g;
	c.fillRect(0, 0, 256, 256);
	c.fillStyle = '#ff5a7a';
	c.beginPath();
	c.arc(128, 110, 70, 0, Math.PI * 2);
	c.fill();
	c.fillStyle = '#ffc94a';
	for (let i = 0; i < 8; i++) c.fillRect(0, 150 + i * 13, 256, 6);
	c.fillStyle = '#3ee0d0';
	c.font = 'bold 44px sans-serif';
	c.fillText('ZONIK', 58, 245);
	return cv;
}

function makeTitle(text) {
	const cv = document.createElement('canvas');
	cv.width = 1024;
	cv.height = 144;
	const c = cv.getContext('2d');
	c.fillStyle = '#fff';
	c.font = 'bold 96px sans-serif';
	c.fillText(text, 48, 106);
	return cv;
}

export class TvPreviewEngine {
	constructor(data) {
		this.data = data;
		this.byId = Object.fromEntries(data.effects.map((e) => [e.id, e]));
		this.canvas = document.createElement('canvas');
		this.canvas.width = MAX_W;
		this.canvas.height = MAX_H;
		const gl = this.canvas.getContext('webgl', { antialias: false, alpha: false });
		if (!gl) throw new Error('WebGL is not available in this browser');
		this.gl = gl;
		this.programs = new Map(); // effect id -> { prog, view } | { error }
		this.targets = new Set(); // registered cards
		this.running = false;
		this.lastFrame = 0;
		this.start = performance.now();
		this.sim = { t: 0, phase: 0.4, spin: 0.2, time: 0.3, kick: 0, kicks: 0,
			rings: [-1, -1, -1, -1], drops: [0, 0, 0, 0, 0, 0, 0, 0], slot: 0, seed: 1 };
		this.setup();
	}

	setup() {
		const gl = this.gl;
		this.quad = gl.createBuffer();
		gl.bindBuffer(gl.ARRAY_BUFFER, this.quad);
		gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 1, -1, -1, 1, 1, 1]), gl.STATIC_DRAW);

		this.texture(0, 0, 0, gl.RGBA, makeCover(), gl.MIRRORED_REPEAT, gl.LINEAR);
		const hm = new Uint8Array(256 * 256);
		for (let i = 0; i < hm.length; i++) {
			const x = i % 256, y = i >> 8;
			hm[i] = 128 + 60 * Math.sin(x * 0.05) * Math.cos(y * 0.07);
		}
		this.texture(1, 256, 256, gl.LUMINANCE, hm, gl.REPEAT, gl.LINEAR);
		this.spectrum = this.texture(2, 64, 1, gl.LUMINANCE_ALPHA, new Uint8Array(128), gl.CLAMP_TO_EDGE, gl.NEAREST);
		this.wave = this.texture(3, 512, 1, gl.LUMINANCE, new Uint8Array(512).fill(128), gl.CLAMP_TO_EDGE, gl.NEAREST);
		this.texture(4, 0, 0, gl.RGBA, makeTitle('Midnight City  ·  M83'), gl.CLAMP_TO_EDGE, gl.LINEAR);
		this.blit = this.compile(this.data.blit);
	}

	texture(unit, w, h, fmt, pixels, wrap, filter) {
		const gl = this.gl;
		const t = gl.createTexture();
		gl.activeTexture(gl.TEXTURE0 + unit);
		gl.bindTexture(gl.TEXTURE_2D, t);
		gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, wrap);
		gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, wrap);
		gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, filter);
		gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, filter);
		if (pixels instanceof HTMLCanvasElement) gl.texImage2D(gl.TEXTURE_2D, 0, fmt, fmt, gl.UNSIGNED_BYTE, pixels);
		else gl.texImage2D(gl.TEXTURE_2D, 0, fmt, w, h, 0, fmt, gl.UNSIGNED_BYTE, pixels);
		return t;
	}

	/** Wraps a shader body in the shared header and footer, as the app does. */
	compile(body) {
		const gl = this.gl;
		const shader = (type, src) => {
			const s = gl.createShader(type);
			gl.shaderSource(s, src);
			gl.compileShader(s);
			if (!gl.getShaderParameter(s, gl.COMPILE_STATUS)) throw new Error(gl.getShaderInfoLog(s) || 'compile failed');
			return s;
		};
		const p = gl.createProgram();
		gl.attachShader(p, shader(gl.VERTEX_SHADER, this.data.vertex));
		gl.attachShader(p, shader(gl.FRAGMENT_SHADER, this.data.header + body + this.data.footer));
		gl.linkProgram(p);
		if (!gl.getProgramParameter(p, gl.LINK_STATUS)) throw new Error(gl.getProgramInfoLog(p) || 'link failed');
		return { id: p, loc: new Map() };
	}

	program(effectId) {
		let entry = this.programs.get(effectId);
		if (!entry) {
			const e = this.byId[effectId];
			try {
				entry = { prog: this.compile(e.body), view: e.view ? this.compile(e.view) : this.blit };
			} catch (err) {
				entry = { error: String(err.message || err) };
				console.warn(`TV preview: ${effectId} failed to compile`, err);
			}
			this.programs.set(effectId, entry);
		}
		return entry;
	}

	/**
	 * Adds a canvas to draw `effectId` into. Returns a handle with setVisible(bool),
	 * setEffect(id) and remove(). The canvas's own width/height set the render size.
	 */
	register(canvas, effectId, onError) {
		const target = { canvas, ctx: canvas.getContext('2d'), effectId, visible: false, fb: null, onError };
		this.targets.add(target);
		this.ensureRunning();
		return {
			setVisible: (v) => { target.visible = v; if (v) this.ensureRunning(); },
			setEffect: (id) => { target.effectId = id; this.freeFeedback(target); },
			remove: () => { this.freeFeedback(target); this.targets.delete(target); },
		};
	}

	freeFeedback(target) {
		if (!target.fb) return;
		const gl = this.gl;
		for (const b of target.fb.buffers) {
			gl.deleteFramebuffer(b.f);
			gl.deleteTexture(b.t);
		}
		target.fb = null;
	}

	/** The pair of buffers a feedback effect reads its last frame from and draws the next into. */
	feedbackBuffers(target, w, h) {
		if (target.fb && target.fb.w === w && target.fb.h === h) return target.fb;
		this.freeFeedback(target);
		const gl = this.gl;
		const make = () => {
			const t = this.texture(7, w, h, gl.RGB, null, gl.CLAMP_TO_EDGE, gl.LINEAR);
			const f = gl.createFramebuffer();
			gl.bindFramebuffer(gl.FRAMEBUFFER, f);
			gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, t, 0);
			gl.clearColor(0, 0, 0, 1);
			gl.clear(gl.COLOR_BUFFER_BIT);
			return { f, t };
		};
		target.fb = { w, h, buffers: [make(), make()] };
		gl.bindFramebuffer(gl.FRAMEBUFFER, null);
		return target.fb;
	}

	ensureRunning() {
		if (this.running) return;
		this.running = true;
		this.lastFrame = performance.now();
		const loop = (now) => {
			if (!this.running) return;
			if (![...this.targets].some((t) => t.visible)) {
				this.running = false; // resumes on the next setVisible(true)
				return;
			}
			if (now - this.lastFrame >= FRAME_MS - 2) {
				const dt = Math.min((now - this.lastFrame) / 1000, 0.1);
				this.lastFrame = now;
				this.step(dt);
				for (const t of this.targets) if (t.visible) this.draw(t);
			}
			requestAnimationFrame(loop);
		};
		requestAnimationFrame(loop);
	}

	destroy() {
		this.running = false;
		for (const t of this.targets) this.freeFeedback(t);
		this.targets.clear();
		this.gl.getExtension('WEBGL_lose_context')?.loseContext();
	}

	/** Advances the simulated song by `dt` seconds, mirroring DemoRenderer.advance(). */
	step(dt) {
		const s = this.sim;
		const gl = this.gl;
		const rand = () => (s.seed = (s.seed * 16807) % 2147483647) / 2147483647;
		const before = Math.floor(s.t / BEAT_SEC);
		s.t += dt;
		if (Math.floor(s.t / BEAT_SEC) > before) {
			s.kick = 1;
			s.kicks++;
			s.rings[s.slot] = 0;
			s.drops[s.slot * 2] = (rand() * 2 - 1) * 1.3;
			s.drops[s.slot * 2 + 1] = (rand() * 2 - 1) * 0.75;
			s.slot = (s.slot + 1) % 4;
		}
		s.kick *= Math.exp(-dt * 6);
		s.rings = s.rings.map((a) => (a < 0 ? a : a + dt > 3 ? -1 : a + dt));
		s.low = 0.35 + 0.45 * s.kick;
		s.mid = 0.4 + 0.2 * Math.sin(s.t);
		s.high = 0.4 + 0.3 * s.kick;
		s.phase = (s.phase + (0.12 + s.low * 0.55 + s.kick * 0.9) * dt) % 2;
		s.spin = (s.spin + (0.012 + s.mid * 0.03) * dt) % 2;
		s.time = (s.time + 0.05 * dt) % 2;

		const sp = new Uint8Array(128);
		for (let i = 0; i < 64; i++) {
			const v = Math.max(0, Math.min(1, (0.9 * Math.exp(-i / 28) + 0.18 * Math.sin(i * 0.8 + s.t * 3) ** 2) * (0.6 + 0.6 * s.kick)));
			sp[i * 2] = v * 255;
			sp[i * 2 + 1] = Math.min(1, v + 0.12) * 255;
		}
		gl.activeTexture(gl.TEXTURE2);
		gl.bindTexture(gl.TEXTURE_2D, this.spectrum);
		gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, 64, 1, gl.LUMINANCE_ALPHA, gl.UNSIGNED_BYTE, sp);
		const wv = new Uint8Array(512);
		for (let i = 0; i < 512; i++) wv[i] = 128 + (60 + 50 * s.kick) * Math.sin(i * 0.09 + s.t * 8) * Math.sin(i * 0.013 + s.t);
		gl.activeTexture(gl.TEXTURE3);
		gl.bindTexture(gl.TEXTURE_2D, this.wave);
		gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, 512, 1, gl.LUMINANCE, gl.UNSIGNED_BYTE, wv);
	}

	draw(target) {
		const entry = this.program(target.effectId);
		if (entry.error) {
			if (!target.failed) {
				target.failed = true;
				target.onError?.(entry.error);
			}
			return;
		}
		const gl = this.gl;
		const e = this.byId[target.effectId];
		const w = Math.min(target.canvas.width, MAX_W);
		const h = Math.min(target.canvas.height, MAX_H);
		if (e.feedback) {
			const fb = this.feedbackBuffers(target, w, h);
			const [prev, next] = fb.buffers;
			gl.bindFramebuffer(gl.FRAMEBUFFER, next.f);
			gl.viewport(0, 0, w, h);
			this.drawWith(entry.prog, w, h, e, prev.t, 0);
			fb.buffers = [next, prev];
			gl.bindFramebuffer(gl.FRAMEBUFFER, null);
			gl.viewport(0, 0, w, h);
			this.drawWith(entry.view, w, h, e, 0, next.t);
		} else {
			gl.bindFramebuffer(gl.FRAMEBUFFER, null);
			gl.viewport(0, 0, w, h);
			this.drawWith(entry.prog, w, h, e, 0, 0);
		}
		// GL draws from the bottom-left, so the w x h picture sits at the bottom of the canvas.
		target.ctx.drawImage(this.canvas, 0, MAX_H - h, w, h, 0, 0, target.canvas.width, target.canvas.height);
	}

	drawWith(prog, w, h, effect, prevTex, srcTex) {
		const gl = this.gl;
		const s = this.sim;
		gl.useProgram(prog.id);
		const loc = (n) => {
			if (!prog.loc.has(n)) prog.loc.set(n, gl.getUniformLocation(prog.id, n));
			return prog.loc.get(n);
		};
		const set = (n, ...v) => {
			const l = loc(n);
			if (l) gl['uniform' + v.length + 'f'](l, ...v);
		};
		const clock = s.t;
		const drift = clock * 0.1;
		set('uAspect', w / h);
		set('uCenter', Math.sin(drift * 3.7) * 0.12, Math.sin(drift * 2.9 + 1.3) * 0.08);
		if (effect.floats) {
			set('uFloat', Math.sin(clock * 0.07) * 0.3 + Math.sin(clock * 0.029 + 2) * 0.05,
				Math.sin(clock * 0.053 + 1.1) * 0.12);
		} else {
			set('uFloat', 0, 0);
		}
		set('uPhase', s.phase);
		set('uSpin', s.spin);
		set('uTime', s.time);
		set('uTwist', Math.sin(drift * 1.3) * 0.06 + s.mid * 0.05);
		set('uLow', s.low);
		set('uMid', s.mid);
		set('uHigh', s.high);
		set('uKick', s.kick);
		const toBeat = BEAT_SEC - (s.t % BEAT_SEC);
		set('uBeat', toBeat < 0.14 ? 1 - toBeat / 0.14 : 0);
		set('uFade', 1);
		set('uWipe', -1);
		set('uWipeSide', 0);
		set('uWipeKind', 0);
		set('uSegments', [6, 8, 10, 12][Math.floor(s.kicks / 16) % 4]);
		set('uKicks', s.kicks % 256);
		set('uPx', 1 / w, 1 / h);
		set('uBlitScale', 1);
		set('uRainbow', 0);
		set('uTitleAspect', 1024 / 144);
		set('uC0', 1, 0.35, 0.48);
		set('uC1', 1, 0.79, 0.29);
		set('uC2', 0.24, 0.88, 0.82);
		// A gentle dive into the Mandelbrot set, looping every minute: single precision gives
		// out long before the TV's perturbation-based dive would.
		set('uZoomCenter', -0.745, 0.1);
		set('uZoomScale', 1.4 * Math.exp(-(clock % 60) * 0.12));
		set('uZoomRot', Math.cos(clock * 0.05), Math.sin(clock * 0.05));
		set('uZoomFlash', 0);
		set('uSkip', 0);
		set('uA', 1, 0);
		set('uZ0', 0, 0);
		set('uCyc0', 0, 0);
		set('uCyc1', 0, 0);
		set('uCyc2', 0, 0);
		set('uPre', 1);
		set('uPer', 1);
		set('uRings', ...s.rings);
		const balls = loc('uBalls');
		if (balls) {
			const b = [];
			for (let i = 0; i < 5; i++) {
				const k = i + 1;
				b.push(Math.sin(clock * (0.61 + 0.13 * k) + k * 1.7) * (w / h) * 0.62,
					Math.cos(clock * (0.47 + 0.11 * k) + k * 2.3) * 0.62,
					[0.3, 0.23, 0.19, 0.15, 0.12][i] * (1 + 0.15 * s.kick));
			}
			gl.uniform3fv(balls, new Float32Array(b));
		}
		const tunnel = loc('uTunnel');
		if (tunnel) {
			const r = [];
			const tt = s.time * Math.PI;
			for (let j = 0; j < 9; j++) {
				const f = (j / 9 + s.phase * 0.5) % 1;
				const z = Math.max(1 - f, 0.03);
				r.push(Math.sin(tt * 2 + z * 4) * 0.35 * z, Math.cos(tt * 4 + z * 3) * 0.35 * z, z);
			}
			gl.uniform3fv(tunnel, new Float32Array(r));
		}
		const drops = loc('uDrops');
		if (drops) gl.uniform2fv(drops, new Float32Array(s.drops));
		for (const [n, unit] of [['uTex', 0], ['uHeight', 1], ['uSpectrum', 2], ['uWave', 3], ['uTitle', 4], ['uPrev', 5], ['uBlit', 6], ['uCur', 6]]) {
			const l = loc(n);
			if (l) gl.uniform1i(l, unit);
		}
		if (prevTex) {
			gl.activeTexture(gl.TEXTURE5);
			gl.bindTexture(gl.TEXTURE_2D, prevTex);
		}
		if (srcTex) {
			gl.activeTexture(gl.TEXTURE6);
			gl.bindTexture(gl.TEXTURE_2D, srcTex);
		}
		gl.activeTexture(gl.TEXTURE0);
		const a = gl.getAttribLocation(prog.id, 'aPos');
		gl.bindBuffer(gl.ARRAY_BUFFER, this.quad);
		gl.enableVertexAttribArray(a);
		gl.vertexAttribPointer(a, 2, gl.FLOAT, false, 0, 0);
		gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4);
	}
}
